### ISSUE TITLE
What are the current results?

### ISSUE THREAD

**Issue by moorepants** [mechmotum/ollie-optimization#16]
Do we have any progress on getting smoother solutions? Any new results to show?

Do we have any idea if we are closer to getting global instead of local solutions?

If so, it'd be great to share the figures with the new results. If not, what's the status?

**Comment by moorepants** [comment]
In the latest commit on master I see:

```
Number of Iterations....: 1494

                                   (scaled)                 (unscaled)
Objective...............:  -8.7563306915034655e-01   -8.7563306915034655e-01
Dual infeasibility......:   2.8506892600677815e-09    2.8506892600677815e-09
Constraint violation....:   3.0006852268407466e-09    3.0006852268407466e-09
Variable bound violation:   9.9890447025074991e-09    9.9890447025074991e-09
Complementarity.........:   1.6585250297866158e-11    1.6585250297866158e-11
Overall NLP error.......:   3.0006852268407466e-09    3.0006852268407466e-09


Number of objective function evaluations             = 3208
Number of objective gradient evaluations             = 1183
Number of equality constraint evaluations            = 3208
Number of inequality constraint evaluations          = 3208
Number of equality constraint Jacobian evaluations   = 1502
Number of inequality constraint Jacobian evaluations = 1502
Number of Lagrangian Hessian evaluations             = 1494
Total seconds in IPOPT                               = 189.277

EXIT: Optimal Solution Found.
      solver  :   t_proc      (avg)   t_wall      (avg)    n_eval
       nlp_f  |  11.39ms (  3.55us)  10.31ms (  3.22us)      3208
       nlp_g  |   2.75 s (856.52us)   2.61 s (813.49us)      3208
  nlp_grad_f  |  35.97ms ( 30.36us)  31.41ms ( 26.51us)      1185
  nlp_hess_l  |   5.68 s (  3.82ms)   5.31 s (  3.57ms)      1487
   nlp_jac_g  |   3.61 s (  2.40ms)   3.37 s (  2.24ms)      1503
       total  | 211.28 s (211.28 s) 189.28 s (189.28 s)         1
```

So whatever test you are running is solving. Are these the noisy solutions still, or now smooth?

**Comment by brocksam** [comment]
> Do we have any progress on getting smoother solutions? Any new results to show?

Not yet. I'm working on this but it's requiring me to understand and rework Jan's code which is taking a while.

> Do we have any idea if we are closer to getting global instead of local solutions?

No idea yet. Will know when I finish reworking the model and we are able to solve successfully.

> If so, it'd be great to share the figures with the new results. If not, what's the status?

I will circulate the results as soon as I'm able to generate them.

> So whatever test you are running is solving. Are these the noisy solutions still, or now smooth?

These are still the results from Jan's thesis so are still noisy and multimodal.

**Comment by moorepants** [comment]
Ok. We soon need to make the call to go with Jan's original results. How about a March 31st deadline to make the call? We are now about a month behind the original idea of having a paper prepared by the end of February.

**Comment by brocksam** [comment]
Yes, I appreciate the time pressure. Can I please request 9th April as I'm away on vacation 25th March - 2nd April which would otherwise only give me another couple of hours on it this evening? I'll make this my top and only priority for work outside of work hours until then. If I have anything sooner than that, even if it's just an indication of progress, I'll update you both.

**Comment by moorepants** [comment]
It shouldn't be work outside of work. I think you, Jan, and I should touch base ASAP. Maybe a call or something.

**Comment by jtheinen** [comment]
> It shouldn't be work outside of work. I think you, Jan, and I should touch base ASAP. Maybe a call or something.

Agreed! let's try and schedule a quick meeting this week. Any date/time this week will do, except for Wednesday afternoon

**Comment by moorepants** [comment]
We went back to Jan's original results.
