### ISSUE TITLE
Change the paper to be active voice

### ISSUE THREAD

**Issue by moorepants** [mechmotum/ollie-optimization#19]
I'm working on editing the paper and we have to change it to active voice. It is quite hard to read in passive voice. In my edits, I will start doing this, but we need to change it fully before submission. It will simplify the writing and reduce the word count significantly by doing so.

**Comment by jtheinen** [comment]
Did you work on this already or shall I do this?

**Comment by moorepants** [comment]
I'm working on it in my PR, but probably will only do so in the places I edit there. To avoid major merge conflicts you may want to wait after my pass (or vice versa).

**Comment by jtheinen** [comment]
Thats good for me! Give me a heads up if you are through it or if you need any help

**Comment by moorepants** [comment]
Significant work to move to mostly active voice was completed.
