### ISSUE TITLE
Remove all figures that we didn't make ourselves

### ISSUE THREAD

**Issue by moorepants** [mechmotum/ollie-optimization#20]
We can't include copyrighted figures/images in the paper without permission. Three options:

1. The figure is CC licensed and maybe we can include it if the journal allows.
2. We remove it (and repalce with our own figure if needed).
3. We ask the copyright holder for permission.

**Comment by jtheinen** [comment]
I checked the figures and I think the only figures that are required that cannot be made ourselves are:

- Fig 1. The figure that shows ollie in steps, could be skipped but I think it is good for the understanding of the ollie
- Fig 3. Motion cue ollie figures
- Fig 9. Maybe world record ollie, but could be skipped possibly

The rest can be deleted or made by me.

I will send out an email to the writers of the paper and the youtube video I took the screenshots from. The world record picture might be difficult as it is an instagram picture. Should I just reach out through instagram?

**Comment by moorepants** [comment]
I think that Figure 1 and 3 are the same. I suggest taking figure 3 only.

> I will send out an email to the writers of the paper and the youtube video I took the screenshots from. The world record picture might be difficult as it is an instagram picture. Should I just reach out through instagram?

Yes. You'll need to have the permission in writing (email can be sufficient) so that we can submit the proof to the journal.

**Comment by jtheinen** [comment]
![image](https://user-images.githubusercontent.com/90770931/234510699-8dd2ac84-cd96-4f9a-971f-d56df98d2fd0.png)

**Comment by moorepants** [comment]
Perfect.

**Comment by brocksam** [comment]
This can be closed with resolving #33.

**Comment by moorepants** [comment]
All figures are either made ourselves or we have obtained permission.
