### ISSUE TITLE
Reduce word count to < 4000 words

### ISSUE THREAD

**Issue by moorepants** [mechmotum/ollie-optimization#21]
This can be a tracking issue for ideas on cutting the words.

- [ ] Move the equations of motion derivation to an appendix (or remove all together).

**Comment by brocksam** [comment]
From submission guidelines: 

- The word limits outlined below refer to the main body of the manuscript text, and do not include the abstract, figure and table captions and references.
- Research articles: A typical research article should have a maximum of 4,000 words with no more than 10 figures and tables in total for effective communication. Longer articles are only allowed based on a foregoing approval from the Editor-in-Chief by emailing a request (before submission) to the JEO assistant (Chitra Vijayaraghavan - [chitra.vijayaraghavan@springernature.com](mailto:chitra.vijayaraghavan@springernature.com)) with proper justification. These requests should only be made in exceptional circumstances. Articles submitted that are longer than 4,000 words without prior approval will be rejected immediately.

**Comment by moorepants** [comment]
This was completed, we are under the word count.
