### ISSUE TITLE
Use Overleaf?

### ISSUE THREAD

**Issue by moorepants** [mechmotum/ollie-optimization#28]
It may make it easier for Eline and Raymund to contribute if we used overleaf.

If you create an overleaf project you can sync it with a git repo. I've done that with other projects, but I think you may have to start at overleaf, getting the git url, then clone on github. You have to manually sync from github or maybe you can setup ci to do it.

Overleaf does resolve the problem of simultaneous editing and it has better ways to make comments and suggest changes.

Thoughts?

**Comment by brocksam** [comment]
I've just done this following [these instructions](https://www.overleaf.com/learn/how-to/Using_Git_and_GitHub) and would recommend to @evanderkruk, it's very easy.


Alternatively, I think we could also collaborate on my Overleaf project for this repo as this would allow us to edit simultaneously without worrying about pulling/committing: https://www.overleaf.com/8597742134dbyzppjqqfbt

**Comment by moorepants** [comment]
I joined on overleaf. Great!. I'll do editing there for the paper.

**Comment by moorepants** [comment]
The file is `paper/ollie-optimization.tex`.

**Comment by moorepants** [comment]
Overleaf says it is down to 2000 words! Maybe my count was incorrect in the last PR.

**Comment by brocksam** [comment]
I've found word counting of `.tex` files to be tricky! For my PhD thesis Overleaf and texcount disagreed by over 10,000 words!

**Comment by brocksam** [comment]
Just had to fix a merge conflict between unmerged Overleaf changes and a non-Overleaf PR from Jan. So my recommendation would be that after anyone's finished an editing session on Overleaf they sync with GitHub to keep this repo up to date. You can do this in the Overleaf "Menu". There's a section called "Sync", within that click on the "GitHub" button.

**Comment by moorepants** [comment]
We can also agree to only make edits to the paper in overleaf, if that helps. Otherwise I think we will be fighting merge conflicts all the time.

**Comment by brocksam** [comment]
I agree. We should agree to only make changes on _my_ Overleaf version (the one linked above).

**Comment by moorepants** [comment]
We are using Overleaf on Sam's account and he is manually pushing changes to this repo for public archival.
