### ISSUE TITLE
Maximum number of figure and tables is 10 it total

### ISSUE THREAD

**Issue by brocksam** [mechmotum/ollie-optimization#32]
TO DO BEFORE CLOSING:
- [x] Merge table 1 ("skateboard variables") into the caption of figure 3 ("skateboard parameterisation").
- [x] Remove figure 4 ("skateboard segments").

See the guidelines: https://www.springer.com/journal/12283/submission-guidelines#Instructions%20for%20Authors_Manuscript%20Submission

**Comment by brocksam** [comment]
To meet the limits I think we need to remove the figure showing the segments used for the inertia calculations, and then merge the two figures labelling the parts of the skateboard and the parameterisation.

**Comment by moorepants** [comment]
that sounds reasonable

**Comment by brocksam** [comment]
@jtheinen and I discussed, we're going to merge table 1 into the caption of the "parameterised skateboard" figure and we're going to delete the "segmented skateboard" figure as it somewhat repeats the "parameterised skateboard" figure. That gets us down to nine total (or 10 if they're harsh counting the first figure as a table and a figure).
