### ISSUE TITLE
Can we use the photo of the world record ollie?

### ISSUE THREAD

**Issue by brocksam** [mechmotum/ollie-optimization#33]
@jtheinen says that it's on instagram, does that make it public and fair use?

Should he:
- message the guy and ask permission?
- who owns the IP, is it the subject or the photographer?

**Comment by moorepants** [comment]
Yes, we have to get written permission from any image we did not create ourselves (unless it has a license or is public domain).

**Comment by moorepants** [comment]
@jtheinen The editor has asked us about the permission of this image. What is the status? If we can't get permission we have to remove the image. The revised paper is due Dec. 20.

**Comment by moorepants** [comment]
Removed the image.
