### ISSUE TITLE
Supporting documents

### ISSUE THREAD

**Issue by brocksam** [mechmotum/ollie-optimization#35]
- [ ] Decide what we want to submit as supporting documents:
    - [ ] PDF of Jan's thesis
    - [ ] Single Python file for optimisations
- [ ] Clean up GitHub repository

**Comment by brocksam** [comment]
Example from another article.

<img width="487" alt="Screenshot 2023-06-13 at 09 17 12" src="https://github.com/mechmotum/ollie-optimization/assets/25300795/64161d1a-23f7-459f-a097-393394ac8bab">

**Comment by moorepants** [comment]
We can simply cite Jan's thesis, it is publicly available. No need to include.

I don't think we really need any supplementary material, except for maybe a video of the animations of the solutions.

If we can prepare the source code that generates the results in the paper, then I recommend making zenodo archive of that and then referencing that.

**Comment by moorepants** [comment]
I included the video file as supplementary materials (only that).

We also link to this repository for the source code.

**Comment by moorepants** [comment]
If either of you want to clean up the git repo and make an archive before we resubmit, that is fine, but not necessary.

**Comment by moorepants** [comment]
Let's just link to this repo in the paper.
