### ISSUE TITLE
ORCID for authors

### ISSUE THREAD

**Issue by brocksam** [mechmotum/ollie-optimization#36]
Find out ORCID for all authors as this is requested by the submission guidelines.

**Comment by moorepants** [comment]
Jason: 0000-0002-8698-6143

**Comment by moorepants** [comment]
Eline: https://orcid.org/0000-0001-6933-0313

Sam: https://orcid.org/0009-0005-2631-0589

**Comment by moorepants** [comment]
I'll make sure these are present in the journal software on the resubmission.
