### ISSUE TITLE
Use of speed vs velocity

### ISSUE THREAD

**Issue by brocksam** [mechmotum/ollie-optimization#37]
I was always taught that speed = scalar quantity and velocity = vector quantity. So if we are not referring to a quantity that has a vector component then we should use speed.

E.g. 

"The first two introduce $\psi_1$, a slack variable representing the magnitude of the relative _speed_ between the foot and the skateboard $\dot{s}_1$."

**Comment by moorepants** [comment]
I agree. speed = scalar, velocity = vector

**Comment by moorepants** [comment]
I just scanned all uses of velocity and speed in the paper and it seems good.
