### ISSUE TITLE
Ensure tables are formatted correctly

### ISSUE THREAD

**Issue by brocksam** [mechmotum/ollie-optimization#38]
- All tables are to be numbered using Arabic numerals.
- Tables should always be cited in text in consecutive numerical order.
- For each table, please supply a table caption (title) explaining the components of the table.
- Identify any previously published material by giving the original source in the form of a reference at the end of the table caption.
- Footnotes to tables should be indicated by superscript lower-case letters (or asterisks for significance values and other statistical data) and included beneath the table body.

**Comment by moorepants** [comment]
The only table is Table 1 and it seems that all is in order.
