### ISSUE TITLE
Change figure 1 to show phases more distinct

### ISSUE THREAD

**Issue by jtheinen** [mechmotum/ollie-optimization#43]
<img width="610" alt="Screenshot 2023-10-04 at 23 10 47" src="https://github.com/mechmotum/ollie-optimization/assets/90770931/ee11004b-4c74-4f5a-b83c-96476689776a">

**Comment by moorepants** [comment]
Now looks like:
![image](https://github.com/mechmotum/ollie-optimization/assets/276007/094f0793-26e6-45f0-b2b4-c56dad2b1ee6)
