### ISSUE TITLE
Clarify nose-tail symmetry

### ISSUE THREAD

**Issue by jtheinen** [mechmotum/ollie-optimization#44]
reviewer 2:

Does [“nose-tail symmetry”](https://github.com/mechmotum/ollie-optimization/blob/4d4e603d48c2a35e80c1d6a072766645e2bfddee/paper/ollie-optimization.tex#L199C91-L199C100) mean the symmetry around the center of gravity along the longitudinal direction?
Probably, I misunderstood.
Fig.3 does not look like the symmetry around the center of gravity along the longitudinal direction.

**Comment by moorepants** [comment]
maybe "geometric symmetry" is helpful? I think your board will always have the mass center a the geometric center right? you could use "geometrically and inertially symmetric" as clarifiers.

**Comment by moorepants** [comment]
>  Fig.3 does not look like the symmetry around the center of gravity along the longitudinal direction.

I think that is just an illusion. The mass center for the board $m_s$ is at the longitudinal geometric center in the figure. I think we can just say that in the rebuttal.

**Comment by moorepants** [comment]
I changed it to "The board was modelled as a simplified popsicle stick skateboard where we assume the board is geometrically symmetric, i.e. the front nose and truck is a mirror of the back tail and truck, and there is no deck concavity." What do you think?
