### ISSUE TITLE
Vertical ground reaction forces EOM

### ISSUE THREAD

**Issue by jtheinen** [mechmotum/ollie-optimization#45]
reviewer 2:
[“During wheel-ground contact, we use a sliding joint for the rear wheel contact to eliminate the ground reaction forces from the equations of motion (EoMs).”
](https://github.com/mechmotum/ollie-optimization/blob/4d4e603d48c2a35e80c1d6a072766645e2bfddee/paper/ollie-optimization.tex#L202)

Probably, I misunderstood.
Were the ground reaction forces in the vertical direction considered?

**Comment by jtheinen** [comment]
I suggest we keep the paper as is for this issue, the original sentence suggests that we do take the forces into account. But just don't have to calculate them.

**Comment by moorepants** [comment]
It's best to make an adjustment for every reviewer comment (even if only minor). This "elimination" of ground reaction forces is being interpreted by the reviewer as not inlcude versus the equation of motion idea that you are saying (that generalized coordinate approach avoids having to have non-contributing forces). Maybe the word "non-contributing forces" can be used to clarify.

**Comment by moorepants** [comment]
I updated it to:

"During the wheel-ground contact phase, we use a sliding joint for the rear wheel ground contact to avoid having to expose the ground reaction forces in the \glspl{eom} derivation."
