### ISSUE TITLE
First appearance CoM

### ISSUE THREAD

**Issue by jtheinen** [mechmotum/ollie-optimization#46]
reviewer 2:
Caption Fig. 3
CoM -> CoM (Center of Mass)
Probably, here is the first appearance of CoM.

**Comment by jtheinen** [comment]
It is not the first appearance:

in figures:
https://github.com/mechmotum/ollie-optimization/blob/4d4e603d48c2a35e80c1d6a072766645e2bfddee/paper/ollie-optimization.tex#L134

in text: 
https://github.com/mechmotum/ollie-optimization/blob/4d4e603d48c2a35e80c1d6a072766645e2bfddee/paper/ollie-optimization.tex#L233C165-L233C178

I get the confusion since we refer to fig 3 before explaining it in the text.

**Comment by moorepants** [comment]
We should spell it out the first time in the text for sure. And if the caption happens to need CoM before it is in the text, then spell it out there too.

**Comment by moorepants** [comment]
This does look like you have it as I just suggested.

You spell out "center of mass" in the caption to Figure 1, it appears next in Figure 3, and then it appears in the text the first time in 2.2 where you spell it out.

I think we just say that it is spelled out the first time it is used in a figure caption and the first time it is used in the text. After that we abbreviate. No changes needed, as @jtheinen suggests.
