### ISSUE TITLE
Clarify backward movement 

### ISSUE THREAD

**Issue by jtheinen** [mechmotum/ollie-optimization#48]
Reviewer 2:
[“Immediately prior to the impact of the tail with the ground, the skateboard rapidly moves backward.”](https://github.com/mechmotum/ollie-optimization/blob/4d4e603d48c2a35e80c1d6a072766645e2bfddee/paper/ollie-optimization.tex#L417)

With respect to the human?

**Comment by jtheinen** [comment]
I suggest describing this phenomenon by replacing backward with "negative x direction"

**Comment by moorepants** [comment]
But, given your figure design, isn't it showing motion relative to the x position of the human?

**Comment by jtheinen** [comment]
The x-motions and y-motions are all absolute. The human is barely moving in x-direction due to the weight difference of the human and the board. I get the confusion due to the spread out images, but the ollie is a standing ollie

**Comment by moorepants** [comment]
Then we need to say "with respect to the human".

**Comment by moorepants** [comment]
I've changed to "Initially, the skateboard moves forward relative to the human. Immediately prior to the impact of the tail with the ground, the skateboard rapidly moves backward with respect to the skater. "

**Comment by moorepants** [comment]
Actually added CoM: "Immediately prior to the
impact of the tail with the ground, the skate-
board rapidly moves backward with respect to
the skater’s CoM."
