### ISSUE TITLE
Figure 8 does not have the same height as the prior two figures

### ISSUE THREAD

**Issue by moorepants** [mechmotum/ollie-optimization#49]
All three simulation figures should be the same size.

**Comment by moorepants** [comment]
@jtheinen can you check this?

**Comment by jtheinen** [comment]
Now the figure does match in size with the other 2. Due to the way of plotting my figures, I had to add some more data points, so the data is slightly denser in x direction. Nonetheless, I think it is better now since the skateboard scale matches with other pictures now.

**Comment by moorepants** [comment]
Great. Looks good to me know.
