### ISSUE TITLE
Incomplete citation

### ISSUE THREAD

**Issue by moorepants** [mechmotum/ollie-optimization#50]
Johnny (2013) Skateboarding Is My
Lifetime Sport: DECK LENGTH
MEASURING BY COMPANY. URL
http://skateboardingismylifetimesport.
blogspot.com/2013/05/
deck-length-measuring-by-company.html

Only first name. Just a URL. Not really an good citation. All caps.

**Comment by moorepants** [comment]
I can't even open the URL:

![image](https://github.com/mechmotum/ollie-optimization/assets/276007/637010a3-2a16-4816-9959-0046b852cb16)

**Comment by moorepants** [comment]
@jtheinen fyi

**Comment by moorepants** [comment]
Note that I have manually edited the bib file extensively to try to correct all the issues with the references. So don't overwrite with a zotero export.

**Comment by jtheinen** [comment]
I still have a copy of the page but it seems that it is taken down...  The page consisted of a person that emailed all big skateboarding companies how they measure the skateboard. Maybe it isn't a reliable source. What would be the right thing to solve it? Should this necessarily be backed up by a citation? 

The claim that is being made is: 
"Boards are measured differently by each brand"

My suggestion is to get rid of this part and the citation. The rest part of the sentence is still backed up by a citation and might be enough to make the point:

"non-specific descriptions such as mellow, steep, and
wide are usually used to communicate deck dimensions to customers"

See pdf attached of local saved website for info on the source.
[deck-length-measuring-by-company.pdf](https://github.com/mechmotum/ollie-optimization/files/13239929/deck-length-measuring-by-company.pdf)

**Comment by moorepants** [comment]
![image](https://github.com/mechmotum/ollie-optimization/assets/276007/1c304725-0969-4dc9-837d-8f3a70cae894)

**Comment by moorepants** [comment]
I think we can just remove the citation but I don't think that "boards are measured differently by each brand" needs to have proof. We can probably leave it, just remove the citation.

**Comment by jtheinen** [comment]
Agreed, I will remove it now

**Comment by jtheinen** [comment]
Citation is gone
