### ISSUE TITLE
Remove `journal-format` directory

### ISSUE THREAD

**Issue by moorepants** [mechmotum/ollie-optimization#52]
I think this is just a copy of the downloaded template, right?

**Comment by brocksam** [comment]
Correct. We can delete that directory. We may also want to remove (or rather, move to a new repo) the `examples/`, `ollie/`, and `tests/` directories, along with a couple of other files, as these only relate to the skateboard modelling package that I started building for this paper but never finished. They're now unrelated to the paper but might be useful to someone in the future for another research project involving skateboard modelling. Are you happy for me to move these?

**Comment by moorepants** [comment]
Sure, or you can leave here and we can just make it clear what it is in the README.
